title: Using pip on Windows
hero_image: images/banner.png
description: Learn about installing Python software on Windows with pip
original_url: https://raspberrypi.org/learning/using-pip-on-windows
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: What is pip?
- title: Do I already have pip?
- title: Is Python in your PATH?
- title: Using pip
- title: What next?
