---
title: Windows में pip का उपयोग
hero_image: images/banner.png
description: Windows पर Python सॉफ्टवेयर pip के साथ स्थापित करना सीखें
original_url: https://raspberrypi.org/learning/using-pip-on-windows
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - title: भूमिका
  - title: आपको किन चीज़ों की आवश्यकता होगी
  - title: Pip क्या है?
  - title: क्या मेरे पास pip पहले से ही मौजूद है?
  - title: क्या आपके PATH में Python है?
  - title: Pip का उपयोग
  - title: आगे क्या?
