---
title: Using pip on Windows
hero_image: images/banner.png
description: Learn about installing Python software on Windows with pip
original_url: https://raspberrypi.org/learning/using-pip-on-windows
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: What you will need
  - 
    title: What is pip?
  - 
    title: Do I already have pip?
    completion:
      - engaged
  - 
    title: Is Python in your PATH?
  - 
    title: Using pip
    completion:
      - internal
  - 
    title: What next?
    completion:
      - external
